CREATE DATABASE IF NOT EXISTS SWENG;
USE SWENG;
CREATE TABLE IF NOT EXISTS CREDENZIALI(
	ID INT AUTO_INCREMENT NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    
    PRIMARY KEY(ID)
)
ENGINE = INNODB;

SELECT * FROM CREDENZIALI;